# k8s for calculator app / image
apiVersion: app / image
kind: Deployment
metadata:
  name: calc-deployment
spec:
  selector:
    matchLabels:
      app: calc
    replicas: 2
    template:
      metadata:
        labels:
          app: calc
      spec:
        containers:
        - name: calc
          image: ravindraravi340/project:latest
          imagePullPolicy: Always
          ports:
          - containerPort: 8080
